name: "Prettier, please!"
on:
  issue_comment:
    types: [created, edited]

jobs:
  prettier-please:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: reiddraper/prettier-please@9ee9f98434a80ac90725481e44f52f88ba953aac
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-user.name: thehub-bot
          git-user.email: thehub-bot@users.noreply.github.com
