name: "Prettier, please!"
on:
  issue_comment:
    types: [created, edited]

jobs:
  prettier-please:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: reiddraper/prettier-please@5eed499eb50279f4744c16bb74013c60f95265aa
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-user.name: thehub-bot
          git-user.email: thehub-bot@users.noreply.github.com
